generation-radius: 1200
server-id: "server1"
export-path: "/mnt/worlds"
seeds-file: "/mnt/seeds/seeds.txt"
spawn-adjustment:
  maxSearchRadius: 100
  maxVerticalScan: 128
cage-building:
  cage-material: PURPLE_STAINED_GLASS
  cage-radius: 4
  cage-height: 3
batch-settings:
  worlds-per-batch: 10
  pause-between-batches: 60
world-delay-ticks: 40