generation-radius: 1200
export-path: "/mnt/hgfs/Worlds"
seeds-file: "/mnt/hgfs/Seeds/seeds.txt"
spawn-adjustment:
  maxSearchRadius: 100
  maxVerticalScan: 128
cage-building:
  cage-material: PURPLE_STAINED_GLASS
  cage-radius: 4
  cage-height: 3